# Generated by Django 6.0.2 on 2026-02-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('assessment', 'Assessment')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teachers.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher'], name='teachers_ac_teacher_5f8dd1_idx'), models.Index(fields=['created_at'], name='teachers_ac_created_20c969_idx')],
                'unique_together': {('teacher', 'activity_type', 'created_at', 'subject', 'class_name')},
            },
        ),
    ]
