# Generated by Django 6.0.2 on 2026-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='teachers_ac_teacher_5f8dd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='teachers_ac_created_20c969_idx',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='class_name',
            new_name='grade',
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_on',
        ),
    ]
